# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5edbea34d1d1f752fae3ce759761e5e050b980bada8c8fd813680fe9e356c546fcad143df4897b2a5758f1493768c90761bfe4e72dd188d30a7ca8543ee14423

test:
  secret_key_base: 63a13d5a8600ddddf9f5c3e560c9aeb6e14491a1287330f0dcdf188fd466158ba2f8ad5c5650e59c57ce9c7c7644b253bd2e2f0f372777a6e3283a42bc5c71af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
